## Base URL - Used primarily on share links
baseURL = '/'

## Directories
assetDir = '/source/assets'
archetypeDir = '/source/archetypes'
layoutDir = '/source/layouts'
staticDir = '/source/static' 
resourceDir = '/source'

## Disables
disableKinds = ['section'] 

## Inline Shortcodes
enableInlineShortcodes = true

## Taxonomies
[taxonomies]
	tag = 'tags'

## Permalinks
[permalinks]
	posts = '/:filename'
	
## Output formats
[outputs]
	home = ['html', 'rss', 'json']

## Layout Parameters
[params]

	## Social Media Data
	title = 'Dragonhouse Stories'
	description = 'Words from D. Travis Lee'
	image = '/dtlee-apple-touch.png'
	
	## Copyright
	copyright = 'All Rights Reserved'
	author = 'D. Travis Lee'
	startYear = 2022
	
	## Language
	lang = 'en-us'
	
	## RSS Limit - number of posts in RSS
	rss = 25
	
	## Pagination size
	paginate = 2
	
	## Related pages maximum - set to 0 to disable related pages
	related = 5
	
	## Taxonomy pagination size
	taxPaginate = 20
	
	## Summary length - length of auto-summaries in RSS, in characters
	sumLen = 150
	
	## Featured post - whether to include a featured post on the homepage
	featured = false
	
	## Robots.TXT file
	robots = true
	
	## Table of contents
	ordered = false
	startLevel = 2
	endLevel = 6
	
	## Theme defaults
	[params.themes]
		defaultColour = "light" ## dark / light
		defaultFont = "serif" ## serif / sans / mono
		defaultSize = 100 ## font-size(%): from 50 to 200 in increments of 10
		defaultSpacing = 130 ## line-height(%): from 100 to 200 in increments of 10
		defaultAlign = "left" ## left / right / justify

[menu]
	[[menu.main]]
		identifier = 'home'
		name = 'Dragonhouse Stories'
		url = '/'
		weight = 1
	[[menu.main]]
		identifier = 'tags'
		url = '/tags/'
		weight = 2
	[[menu.main]]
		identifier = 'about'
		url = '/about/'
		weight = 3
	[[menu.main]]
		identifier = 'rss'
		url = '/rss/'
		weight = 4
	[[menu.main]]
		identifier = 'settings'
		url = '/settings/'
		weight = 5
		[[menu.main.params]]
			class = 'js-only'
			isSettings = true
	[[menu.main]]
		identifier = 'search'
		url = '/search/'
		weight = 6
		[[menu.main.params]]
			class = 'js-only'
			disable = false
			
## Related Posts Settings
[related]
	includeNewer = true
	threshold = 50
	toLower = true
	[[related.indices]]
		applyFilter = false
		cardinalityThreshold = 0
		name = 'keywords'
		pattern = ''
		toLower = false
		type = 'basic'
		weight = 100
	[[related.indices]]
		applyFilter = false
		cardinalityThreshold = 0
		name = 'tags'
		pattern = ''
		toLower = false
		type = 'basic'
		weight = 80
			
## Markup Settings - unsafe toggle
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true